name: tweet-3times-a-day
on:
  workflow_dispatch:
  schedule:
    # UTC → JST(+9) で 00,08,16 時に相当
    - cron:  '0 15 * * *'   # 00:00 JST
    - cron:  '0 23 * * *'   # 08:00 JST
    - cron:  '0 9 * * *'   # 18:00 JST
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          API_KEY:        ${{ secrets.API_KEY }}
          API_SECRET:     ${{ secrets.API_SECRET }}
          ACCESS_TOKEN:   ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET:  ${{ secrets.ACCESS_SECRET }}
          SHEET_URL:      ${{ secrets.SHEET_URL }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
