name: tweet-5times-a-day         # ← 任意に変更

on:
  workflow_dispatch:             # 手動実行
  schedule:
    # ───────── 投稿 5 回 / 日 (JST) ─────────
    - cron: '0 15 * * *'   # 00:00 JST (= 15:00 UTC 前日)
    - cron: '0 21 * * *'   # 06:00 JST
    - cron: '0 3  * * *'   # 12:00 JST
    - cron: '0 9  * * *'   # 18:00 JST
    - cron: '0 14 * * *'   # 23:00 JST

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          API_KEY:              ${{ secrets.API_KEY }}
          API_SECRET:           ${{ secrets.API_SECRET }}
          ACCESS_TOKEN:         ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET:        ${{ secrets.ACCESS_SECRET }}
          SHEET_URL:            ${{ secrets.SHEET_URL }}
          GOOGLE_SERVICE_JSON:  ${{ secrets.GOOGLE_SERVICE_JSON }}
